# -*- coding: utf-8 -*-
"""Assignment2.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lAM4Z1L6q3LvnI3LJ4jy_be33iXpVqAR
"""

#1.What are the two values of the Boolean data type? How do you write them?

---->
There are 2 boolen data types:
1.TRUE
2.FALSE
and TRUE is always 1
and fALSE is alwyas 0

we write boolen data type using 'bool' andd it will only take true and false value.

#2. What are the three different types of Boolean operators?
---->
There are 3 boolen operator :
1.AND
2.OR
3.NOT

#3. Make a list of each Boolean operator truth tables (i.e. every possible combination of Boolean values for the operator and what it evaluate ).

----->

 True and True =True.

True and False = False.

False and True = False.

False and False = False.

True or True = True.

True or False = True.

False or True = True.

False or False = False.

not True = False.

not False is True.

#4. What are the values of the following expressions?

print((5>4) and (3==5))
print(not(5>4))
print((5>4) or (3==5))
print(not(5>4) or (3==5))
print((True and True) and (True==False))
print((not(False))or(not(True)))


---->
False
False
True
False
False
True

#5. What are the six comparison operators?

The 6 comparison operator are given below:

==
!=
>
<
>=
<=

#6. How do you tell the difference between the equal to and assignment operators?Describe a condition and when you would use one.

'==' operator compare 2 values where '=' store the value.
eg:
a=3
b=3
if (a==b):
  print("true")
else:
  print("false")
 
 Now the '==' will compare values of a and b and then print true coz it hold same data.

but now,

a=3
means a hold the data [int] 3.

#7. Identify 3 blocks in this code.
spam = 0
if spam == 10:
    print('eggs') #Block 1
if spam > 5:
    print('bacon') #Block 2
else:
    print('ham') #Block 3
    print('spam')
    print('spam')



    The output will be :
    'ham'
    'spam'
    'spam'

#8. Write code that prints Hello if 1 is stored in spam, prints Howdy if 2 is stored in spam, and prints Greetings! if anything else is stored in spam.

spam=int(input())
if (spam==1):i
  print("Hello")
elif (spam==2):
  print("Howdy")
else:
  print("Greeting")

#9.If your programme is stuck in an endless loop, what keys you’ll press?


----->
I will press ctrl+c.

#10. How can you tell the difference between break and continue?

break:
It will break the loop , when we enter break statment.
continue:
It will continue the loop 
for eg:

for i in range(5):
  if (i==3):
    break
    ---> so it will print till 3 and break the loop
 
 BUT:

for i in range(5):
  if (i==3):
    continue
    ---> it will not break on 3 , it will continue loop till printing 4.

#11. In a for loop, what is the difference between range(10), range(0, 10), and range(0, 10, 1)?

In range(10)  it means it will print 0 to 9.
In range(0,10) it means it will print 0 to 9.
In range(0,10,1) it means it will print 0 to 9 with the gap of 1 digit like(0,2,4,6,8)

#12. Write a short program that prints the numbers 1 to 10 using a for loop. Then write an equivalent program that prints the numbers 1 to 10 using a while loop.

for i in range(1,11):
  print(i)

#using while loop

a=1
while a<=10:
  print(a)
  a=a+1

#13. If you had a function named bacon() inside a module named spam, how would you call it after importing spam?

user can call it by using 'spam.bacon()'.